image_width: 352
image_height: 288
exposure: 10
D_thresh: 11
one_one_diff: 0.3
scale_percent: 100
device_name: "/dev/video0"
meas_noise: 0.1
proc_noise_pos: 0.5
proc_noise_vel: 0.5
tracking_thres: 5
lost_dt: 0.5
max_region_err: 5
use_serial: false
serial_device: "/dev/ttyACM0"
use_saver: false
roi_target_w: 171
roi_target_h: 144